### ISSUE TITLE
Logo 2 not viewable

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/storytelling#1]
Logo 2 is not viewable. Below is link to file.

https://github.com/citizenlabsgr/brand/blob/master/logo/Logo-02.png

**Comment by BrandonKlotz** [comment]
That is because it is a white logo on a transparent background.

**Comment by BrandonKlotz** [comment]
In the readme we can put it on a different color background.

**Comment by jacebrowning** [comment]
When do we expect a white logo to be used?

**Comment by Allen616** [comment]
Will label in readme that this logo is  white logo on a transparent background.
