### ISSUE TITLE
Write a one-sentence summary of what Citizen Labs does that all of us can remember and recite

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/storytelling#6]
> Empowering citizens to improve their communities and local government.

> Empowering people to improve their communities and local government (through ... open data and open source projects).

**Comment by Allen616** [comment]
We have had some discussion on this as a draft amongst board members:

> Empowering citizens to improve their communities and local government.

Happy to have additional conversations.

**Comment by jacebrowning** [comment]
At Weekend for Good I ended up using:

> Citizen Labs empowers individuals to engage with their communities and local governments.

**Comment by Allen616** [comment]
Can also just use people = individuals.

> Empowering people to improve their communities and local government.

**Comment by jacebrowning** [comment]
I think "citizens" is OK, especially if we define it on the homepage, but it was just awkward to say "Citizen Labs empowers citizens...". 😄 

As tag line, I also like:

> Empowering people to improve their communities and local government (through ...)
